bundler_args: --without development
language: ruby
rvm:
  - rbx-19mode
  - jruby-19mode
  - 1.9.2
  - 1.9.3
  - 2.0.0
services:
  - redis-server
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: jruby-18mode
    - rvm: 1.8.7
